;A TO D ,CONVERTS Vanalog @ AN0 AND REFLECTS  UPPER BYTE OF RESULT AT PORT C
;GOWTHAM_SHANMUGARAJ
	list p=16F877a
	include p16F877a.inc	
      ORG	00			    	;START AT 00
    BSF	STATUS,5	    	;BANK 1
	  BCF	STATUS,6
	  BSF	TRISA,0		      ;ANALOG INPUT CHANNEL AS INPUT
	  CLRF	TRISC		    	;INITIALIZE PORT C
	  MOVLW	B'01000000'	  ;LEFT JUSTIFIED RESULT,FOSC/4,AN0, Vref + = Vs, Vref  - =0v 
	  MOVWF	ADCON1
	  BCF	STATUS,5	    	;BANK 0
CONVERT
	  MOVLW	B'00000001'	  ;SWITCH ON ADC BUT DONT START CONVERSION
	  MOVWF	ADCON0
                        ;INTRODUCE DELAY FOR ACQISITION TIME
		movlw	0X05		      ;	0X0a* 4 Us Delay
		movwf 0x20		      ;0x20 is a general RAM LOCATION
del1	nop
		decfsz	0x20,1
	  goto	del1
	  BSF	ADCON0,GO
	  BTFSC ADCON0,2      ;wait for conversion to complete
	  GOTO	$-1
	  MOVF	ADRESH,0	  	;TRANSFER UPPER BYTE OF RESULT TO PORT C
	  MOVWF	PORTC
	  GOTO	CONVERT	    	;DO AGAIN
	  END					        ;END OF INSTRUCTIONS



