;TRANSMITS  I2C_TX_WORD  TO SLAVE
;UPON INTERRUPT RECEIVES FROM SLAVE AND STORES IT IN	I2C_RX_WORD
;TRANSFERS I2C_RX_WORD TO PORT D (for diagnostic purposes)
	

	list p=16F877a
	include p16F877a.inc
;SPECIFY LABELS FOR RAM
I2C_RX_WORD	EQU	33
I2C_ADD	EQU	34 
I2C_TX_WORD	EQU	35	
	ORG	00
	GOTO	START
	ORG	04 
	GOTO	INTERRUPT_SERVICE_ROUTINE
START	BCF	STATUS,6			;BANK 1
		BSF	STATUS,5
		MOVLW	B'00000000'
		MOVWF	TRISD
		MOVLW	B'10011000'		;I2C BITS INPUT
		MOVWF	TRISC
		MOVLW	07				;BAUD RATE 125KHZ
		MOVWF	SSPADD
;INITIALIZING SFR IN BANK 0
		BCF	STATUS,5			;BANK 0
		MOVLW	B'11110000'
		MOVWF	I2C_TX_WORD
		MOVLW	B'00101000'		;SSPCON1:MSSP ON,I2C MASTER
		MOVWF	SSPCON

;SEND OPENING STRING
		MOVLW	0XA4
		MOVWF	I2C_ADD
		CALL	I2C_SEND_ADD
		MOVWF	I2C_TX_WORD
		CALL	I2C_SEND_WORD
		CALL	I2C_SEND_STOP
;RECEIVE FROM SLAVE ON EXTERNAL INTERRUPT
;ENABLE INTERRUPTS
		BCF	INTCON,INTF
		BSF	INTCON,INTE
		BSF	INTCON,GIE
LOOP_ONE	GOTO	LOOP_ONE
;ISR BEGINS HERE
INTERRUPT_SERVICE_ROUTINE	
					MOVLW	0XA5
					MOVWF	I2C_ADD
					CALL		I2C_SEND_ADD
					CALL	I2C_REC_WORD
					CALL	I2C_SEND_STOP
					MOVF	I2C_REC_WORD,0
					MOVWF	PORTD

		
		
;SUB ROUTINES
I2C_SEND_ADD	BSF	STATUS,5		;BANK 1
					BSF	SSPCON2,SEN
					BTFSC	SSPCON2,SEN
					GOTO	$-1
					BCF	STATUS,5		;BANK 0
					MOVF	I2C_ADD,0
					MOVWF	SSPBUF
					BCF	PIR1,SSPIF
					BSF	STATUS,5		;BANK 1
					BTFSC	SSPSTAT,BF
					GOTO	$-1
					BTFSC	SSPCON2,ACKSTAT
					GOTO	$-1
					BCF	STATUS,5		;BANK 0
					BTFSS	PIR1,SSPIF
					GOTO	$-1
					BCF	PIR1,SSPIF
					RETURN
I2C_SEND_WORD	BCF	STATUS,5		;ENSURE IN BANK 0
					MOVF	I2C_TX_WORD,0
					MOVWF	SSPBUF
					BSF	STATUS,5		;BANK 1
					BTFSC	SSPSTAT,R_W
					GOTO	$-1
					BTFSC	SSPCON2,ACKSTAT
					GOTO	$-1
					BCF	STATUS,5		;BANK 0
					RETURN	
I2C_REC_WORD	BSF	STATUS,5	;BANK 1
					BSF	SSPCON2,RCEN
					BTFSS	SSPSTAT,BF
					GOTO	$-1
					BCF	STATUS,5	;BANK 0
					MOVF	SSPBUF,0
					MOVWF	I2C_RX_WORD
					BCF	PIR1,SSPIF
					BSF	STATUS,5	;BANK 1
					BSF	SSPCON2,ACKDT
					BSF	SSPCON2,ACKEN
					BCF	STATUS,5	;BANK 0
					BTFSS	PIR1,SSPIF
					GOTO	$-1
					BCF	STATUS,5	;BANK 0
					RETURN	
I2C_SEND_STOP	BSF	STATUS,5	;BANK 1
					BSF	SSPCON2,PEN
					BTFSS	SSPSTAT,P
					GOTO	$-1
					BCF	STATUS,5	;BANK O
					RETURN
					END
		




	
