;TRANSMITS  PORT D TO MASTER UPON REQUEST
;REFLECTS I2C_RX_WORD ON PORT B
	list p=16F877a
	include p16F877a.inc
	I2C_TX_WORD EQU	34
	I2C_RX_WORD	EQU	36
	ORG	00
	GOTO	START
	ORG	04
	GOTO	INTERRUPT_SERVICE_ROUTINE
START	BCF	STATUS,6
	BSF	STATUS,5
	MOVLW	B'00000000'
	MOVWF	TRISB
	MOVWF	B'11111111'		;DIAGNOSTIC PURPOSE
	MOVWF	TRISD
	MOVLW	B'00011000'
	MOVWF	TRISC
	MOVLW	B'10100100'
	MOVWF	SSPADD
	BSF	PIE1,SSPIE
;INITIALISE SFR IN BANK 0
	BCF	STATUS,5
	MOVLW	B'00110110'
	MOVWF	SSPCON
;ENABLING GLOBAL INTERRUPTS
	BSF	INTCON,GIE
	BSF	INTCON,PEIE
LOOP_ONE	GOTO	LOOP_ONE
;ISR BEGINS HERE
INTERRUPT_SERVICE_ROUTINE
		BSF	STATUS,5
		BTFSC	SSPSTAT,D_A
		GOTO	ISR_ONE
		BCF	STATUS,5
		MOVF	SSPBUF,0
		BSF	STATUS,5
		BTFSC	SSPSTAT,R_W
		GOTO	SEND_I2C
		BCF	STATUS,5
		BCF	PIR1,SSPIF
		RETFIE
ISR_ONE	BCF	STATUS,5
			MOVF	SSPBUF,0
			MOVWF	I2C_RX_WORD
			MOVF	I2C_RX_WORD,0
			MOVWF	PORTB
			BCF	PIR1,SSPIF
			RETFIE
SEND_I2C	BCF	STATUS,5
			MOVF	PORTD,0
			MOVWF	I2C_TX_WORD
			MOVF	I2C_TX_WORD,0
			MOVWF	SSPBUF
			BSF	SSPCON,CKP
			BTFSS	PIR1,SSPIF
			GOTO	$-1
			BCF	PIR1,SSPIF
			RETFIE
			END
			

		
							
