;USES TIMER1 TO PRODUCE SQUARE WAVE ON PORT C PIN 0
;NO SOFTWARE DELAY ROUTINES USED
;BY GOWTHAM_SHANMUGARAJ


LIST	p=16F877a
INCLUDE	p16F877a.inc   
	ORG	00
	GOTO	START
	ORG	04
	GOTO	INTERRUPT_SERVICE_ROUTINE

START BSF	STATUS,5					;BANK 1
		  BCF	STATUS,6
			MOVLW	B'00000000'				;PORT C ALL BITS OUTPUT
			MOVWF	TRISC
			MOVLW	B'11000000'				;GENERAL  & PHERIPHERAL INTERRUPT ENABLE
			MOVWF	INTCON
			MOVLW	B'00000001'				;TIMER1 INTERRUPT ENABLE
			MOVWF	PIE1
			BCF	STATUS,5				   	;BANK O
			BCF	STATUS,6
			MOVLW	00						    ;INITIALIZE TIMER 1 REGISTERS (upper and lower)			
			MOVWF	TMR1H
			MOVLW	00
			MOVWF	TMR1L
			MOVLW	B'00000001'				;TIMER 1 on,internalclock(FOSC/4),pre-scalar 1:1
			MOVWF	T1CON

LOOP		GOTO	LOOP					  ;WAIT FOR TIMER1 INTERRUPT

INTERRUPT_SERVICE_ROUTINE 	
			BCF	PIR1,TMR1IF				   ;CLEAR TIMER 1 INTERRUPT FLAG
			INCF	0X20,1						 ;TOGGLE PORT C BIT 0 on  EVERY INTERUPT(thus producing square wave)
			BTFSC	0X20,0
			BCF	PORTC,0
			BTFSS	0X20,0
			BSF	PORTC,0
			RETFIE							    	;RETURN FROM INTERRUPT

			END								        ;END OF INSTRUCTIONS
			
