;TRANSFERS PORTD TO PORTC OF THE SAME PIC VIA USART IN ASYNC MODE
;RX AND TX ARE ELECTRICALLY SHORTED FOR THIS PURPOSE	
;GOWTHAM_SHANMUGARAJ
	list p=16F877a
	include p16F877a.inc
	ORG	00					;START AT 00
	BSF	STATUS,5			;BANK	1
	BCF	STATUS,6
	MOVLW	00				;PORT B ALL BITS OUTPUT
	MOVWF	TRISB	
	MOVLW	B'11111111'	  	;PORT D ALL BITS INPUT
	MOVWF	TRISD
	BSF	TRISC,7			;RX INPUT,TX OUTPUT
	BCF	TRISC,6
	MOVLW	B'00100100'		;set up async channel:transmit enabled, 8-bit,highspeed baud rate
	MOVWF	TXSTA
	MOVLW	04				;50kbps
	MOVWF	SPBRG
	BCF	STATUS,5			;bank 0
	MOVLW	B'10010000'		;continuous receiving, no address detect
	MOVWF	RCSTA
   LOOP_ONE
;SEND
	BCF	PIR1,RCIF               ;PRE CLEAR RECEIVE INTERRUPT FLAG
	MOVF	PORTD,W			;MOVE PORT D TO TXREG AND SEND
	MOVWF	TXREG
;RECIEVE
	BTFSS	PIR1,RCIF			;CHECK INTERRUPT FLAG
	GOTO	$-1					;WAIT UNTIL RECEIVE COMPLETE
	MOVF	RCREG,W			;MOV RECEIVED VALUES TO PORTB
	MOVWF	PORTB
	GOTO	LOOP_ONE		;REPEAT INFINETLY
	END						;END OF INSTRUCTIONS
	
